### ISSUE TITLE
18 -- Hello, jQuery--The Washington Redskins

### ISSUE THREAD

**Issue by mfees** [mfees/TIY-TodoMVC#1]
- [ ] _WIP Issue:_ `18 --Hello JQuery` with: (M)
  - [x] come up with awesome team name
  - [x] checkpoints, features, and estimates!
  - [x] JQuery Video- Everyone Watches
  - [ ] Evan & Garrett watch 'Go Fund Yourself'
- [ ] _WIP Branch:_ `TIY-TodoMVC:master`
  - [ ] from `feature/` branches to `master`
- [ ] ToDoMVC (XL)
  - [ ] feature/02--textbox (L)
    - [x] append input to list
    - [ ] autofocus
    - [ ] hide `#main` & `#footer`
  - [ ] feature/03--container (L)
    - [ ] change class on completed checkboxes- `.toggle()`
    - [x] delete todo item
  - [ ] feature/04--bottom--options (L)
    - [ ] clear completed
    - [ ] All- shows all todo
    - [ ] Active- shows only the active tasks
    - [ ] Completed- shows only completed tasks
  - [ ] feature/05--major--cleanup (L)
    - [ ] connecting lose ends from section to section
    - [ ] making things look pretty if needed
- [ ] PR from feature branch (S)
  - [ ] two :+1: from peers per PR
  - [ ] link to WIP Issue on each PR
  - [ ] hate life

**Comment by jrutishauser** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/231

**Comment by mfees** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/221

**Comment by eklemen** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/228

**Comment by GarrettGraham** [comment]
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/227
